### ISSUE TITLE
Errinho

### ISSUE THREAD

**Issue by pvfreitas** [deniscsz/Magento-Sigep#1]
Denis, obrigado por compartilhar o módulo! Ele está estável? 
Testei num ambiente de desenvolvimento. Selecionei um pedido no grid e apontei pra "Export layout to Sigep". Gerou um txt chamado "tmplayout.sigepweb.txt". 

No final desse arquivo recebi o seguinte erro:
script type="text/javascript">window.location.href = 'http://xxx/xxx/loja/errors/report.php?id=1171464092972';

Olhei nesse report e lá consta:
a:5:{i:0;s:53:"Cannot send headers; headers already sent in , line 0";i:1;s:1433:"#0 /var/www/xxx/loja/lib/Zend/Controller/Response/Abstract.php(148): Zend_Controller_Response_Abstract->canSendHeaders(true)

Saberia dizer o motivo do erro?

**Comment by phdiegues** [comment]
Ainda não desisti, rss alguém poderia me dar uma força?

**Comment by deniscsz** [comment]
Olá @phdiegues. Obrigado por não desistir rsrs.
Qual a versão do seu Magento? Pergunto para eh tentar simular. Ou então envie o acesso do seu ambiente de teste para deniscsz+github@gmail.com que eu verifico para você. Abraço.

**Comment by phdiegues** [comment]
Olá denis utilizo a versão Magento versão. 1.8.0.0

Este erro está acontecendo no ambiente de produção, estou sem o ambiente de testes

**Comment by phdiegues** [comment]
Vou enviar o arquivo gerado pelo modulo lá no email

**Comment by deniscsz** [comment]
Ok.

Denis Colli Spalenza

Em 5 de novembro de 2015 13:10, phdiegues <notifications@github.com>
escreveu:

**Comment by phdiegues** [comment]
Big Artesanato


 Bom dia Denis, tudo bem?

 

Recebeu os acessos certinho?

 

Att.


Big Artesanato

 

De: Denis Colli Spalenza [mailto:notifications@github.com] 
Enviada em: quinta-feira, 5 de novembro de 2015 09:04
Para: deniscsz/Magento-Sigep
Cc: phdiegues
Assunto: Re: [Magento-Sigep] Errinho (#1)

 

Olá @phdiegues <https://github.com/phdiegues> . Obrigado por não desistir rsrs.
Qual a versão do seu Magento? Pergunto para eh tentar simular. Ou então envie o acesso do seu ambiente de teste para deniscsz+github@gmail.com que eu verifico para você. Abraço.

—
Reply to this email directly or view <https://github.com/deniscsz/Magento-Sigep/issues/1#issuecomment-154031142>  it on GitHub.  <https://github.com/notifications/beacon/AGDCs-KAUtqEFBtWbKfw1QZrYBxH08JDks5pCy8RgaJpZM4BJhLS.gif> 



---
Este email foi escaneado pelo Avast antivírus.
https://www.avast.com/antivirus

**Comment by deniscsz** [comment]
Oi PH, bom dia.

Recebi sim. Provavelmente vou mexer hoje a noite, quando terei mais tempo
livre.

Assim que eu acertar te aviso.

Abraço.

Denis Colli Spalenza

Em 6 de novembro de 2015 09:25, phdiegues <notifications@github.com>
escreveu:

**Comment by phdiegues** [comment]
Big Artesanato


 Beleza, brigadão.


Big Artesanato

 

De: Denis Colli Spalenza [mailto:notifications@github.com] 
Enviada em: sexta-feira, 6 de novembro de 2015 09:39
Para: deniscsz/Magento-Sigep
Cc: phdiegues
Assunto: Re: [Magento-Sigep] Errinho (#1)

 

Oi PH, bom dia.

Recebi sim. Provavelmente vou mexer hoje a noite, quando terei mais tempo
livre.

Assim que eu acertar te aviso.

Abraço.

Denis Colli Spalenza

Em 6 de novembro de 2015 09:25, phdiegues <notifications@github.com>
escreveu:

>
>
>
>
>
> Big Artesanato
>
>
> Bom dia Denis, tudo bem?
>
>
>
> Recebeu os acessos certinho?
>
>
>
> Att.
>
>
> Big Artesanato
>
>
>
> De: Denis Colli Spalenza [mailto:notifications@github.com]
> Enviada em: quinta-feira, 5 de novembro de 2015 09:04
> Para: deniscsz/Magento-Sigep
> Cc: phdiegues
> Assunto: Re: [Magento-Sigep] Errinho (#1)
>
>
>
> Olá @phdiegues <https://github.com/phdiegues> . Obrigado por não desistir
> rsrs.
> Qual a versão do seu Magento? Pergunto para eh tentar simular. Ou então
> envie o acesso do seu ambiente de teste para deniscsz+github@gmail.com
> que eu verifico para você. Abraço.
>
> —
> Reply to this email directly or view <
> https://github.com/deniscsz/Magento-Sigep/issues/1#issuecomment-154031142>
> it on GitHub. <
> https://github.com/notifications/beacon/AGDCs-KAUtqEFBtWbKfw1QZrYBxH08JDks5pCy8RgaJpZM4BJhLS.gif>
>
>
>
>
> ---
> Este email foi escaneado pelo Avast antivírus.
> https://www.avast.com/antivirus
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deniscsz/Magento-Sigep/issues/1#issuecomment-154385920>
> .
>



—
Reply to this email directly or view <https://github.com/deniscsz/Magento-Sigep/issues/1#issuecomment-154390204>  it on GitHub.  <https://github.com/notifications/beacon/AGDCsyc3DaQRiB2o-9PRI-r-1L1r36BOks5pDIjEgaJpZM4BJhLS.gif> 



---
Este email foi escaneado pelo Avast antivírus.
https://www.avast.com/antivirus

**Comment by phdiegues** [comment]
Big Artesanato


 Cara, desculpa te encher aí, mas consegui gerar o log de erro hoje, só mesmo pra te adiantar. Segue:

 

 

a:5:{i:0;s:157:"Cannot send headers; headers already sent in /home/bigartes/public_html/app/code/community/Xpd/Sigep/controllers/Adminhtml/Sales/OrderController.php, line 75";i:1;s:1393:"#0 /home/bigartes/public_html/lib/Zend/Controller/Response/Abstract.php(148): Zend_Controller_Response_Abstract->canSendHeaders(true)

#1 /home/bigartes/public_html/app/code/core/Mage/Core/Controller/Response/Http.php(106): Zend_Controller_Response_Abstract->setRedirect('https://www.big...', 302)

#2 /home/bigartes/public_html/app/code/core/Mage/Adminhtml/Controller/Action.php(348): Mage_Core_Controller_Response_Http->setRedirect('https://www.big...')

#3 /home/bigartes/public_html/app/code/community/Xpd/Sigep/controllers/Adminhtml/Sales/OrderController.php(79): Mage_Adminhtml_Controller_Action->_redirect('*/*/')

#4 /home/bigartes/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Xpd_Sigep_Adminhtml_Sales_OrderController->exporttosigepAction()

#5 /home/bigartes/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('exporttosigep')

#6 /home/bigartes/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))

#7 /home/bigartes/public_html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()

#8 /home/bigartes/public_html/app/Mage.php(683): Mage_Core_Model_App->run(Array)

#9 /home/bigartes/public_html/index.php(87): Mage::run('', 'store')

#10 {main}";s:3:"url";s:80:"/index.php/admin/sales_order/exporttosigep/key/134dd9568e3b5da7983d04ba30a27a3d/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}

 

 

Abração.


Big Artesanato

 

De: Denis Colli Spalenza [mailto:notifications@github.com] 
Enviada em: sexta-feira, 6 de novembro de 2015 09:39
Para: deniscsz/Magento-Sigep
Cc: phdiegues
Assunto: Re: [Magento-Sigep] Errinho (#1)

 

Oi PH, bom dia.

Recebi sim. Provavelmente vou mexer hoje a noite, quando terei mais tempo
livre.

Assim que eu acertar te aviso.

Abraço.

Denis Colli Spalenza

Em 6 de novembro de 2015 09:25, phdiegues <notifications@github.com>
escreveu:

>
>
>
>
>
> Big Artesanato
>
>
> Bom dia Denis, tudo bem?
>
>
>
> Recebeu os acessos certinho?
>
>
>
> Att.
>
>
> Big Artesanato
>
>
>
> De: Denis Colli Spalenza [mailto:notifications@github.com]
> Enviada em: quinta-feira, 5 de novembro de 2015 09:04
> Para: deniscsz/Magento-Sigep
> Cc: phdiegues
> Assunto: Re: [Magento-Sigep] Errinho (#1)
>
>
>
> Olá @phdiegues <https://github.com/phdiegues> . Obrigado por não desistir
> rsrs.
> Qual a versão do seu Magento? Pergunto para eh tentar simular. Ou então
> envie o acesso do seu ambiente de teste para deniscsz+github@gmail.com
> que eu verifico para você. Abraço.
>
> —
> Reply to this email directly or view <
> https://github.com/deniscsz/Magento-Sigep/issues/1#issuecomment-154031142>
> it on GitHub. <
> https://github.com/notifications/beacon/AGDCs-KAUtqEFBtWbKfw1QZrYBxH08JDks5pCy8RgaJpZM4BJhLS.gif>
>
>
>
>
> ---
> Este email foi escaneado pelo Avast antivírus.
> https://www.avast.com/antivirus
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deniscsz/Magento-Sigep/issues/1#issuecomment-154385920>
> .
>



—
Reply to this email directly or view <https://github.com/deniscsz/Magento-Sigep/issues/1#issuecomment-154390204>  it on GitHub.  <https://github.com/notifications/beacon/AGDCsyc3DaQRiB2o-9PRI-r-1L1r36BOks5pDIjEgaJpZM4BJhLS.gif> 



---
Este email foi escaneado pelo Avast antivírus.
https://www.avast.com/antivirus

**Comment by phdiegues** [comment]
Big Artesanato


 CONSEGUI DENIS!!!!!!

 

Brigadão pelas dicas cara. Parabens pelo modulo, companho vc pela net e vc manja muito.

 

Veja a respeito dos ajustes em meu site se da pra vc pegar tb, vamos fazer um orçamento

Abração.


Big Artesanato

 

De: Denis Colli Spalenza [mailto:notifications@github.com] 
Enviada em: quinta-feira, 5 de novembro de 2015 09:04
Para: deniscsz/Magento-Sigep
Cc: phdiegues
Assunto: Re: [Magento-Sigep] Errinho (#1)

 

Olá @phdiegues <https://github.com/phdiegues> . Obrigado por não desistir rsrs.
Qual a versão do seu Magento? Pergunto para eh tentar simular. Ou então envie o acesso do seu ambiente de teste para deniscsz+github@gmail.com que eu verifico para você. Abraço.

—
Reply to this email directly or view <https://github.com/deniscsz/Magento-Sigep/issues/1#issuecomment-154031142>  it on GitHub.  <https://github.com/notifications/beacon/AGDCs-KAUtqEFBtWbKfw1QZrYBxH08JDks5pCy8RgaJpZM4BJhLS.gif> 



---
Este email foi escaneado pelo Avast antivírus.
https://www.avast.com/antivirus

**Comment by deniscsz** [comment]
Oi PH.

Fico feliz que deu certo, parabéns :)
Eu não cheguei a olhar ainda mas o que você mudou?
Se tinha algo errado seria um prazer colocar sua contribuição lá no github
para ajudar mais pessoas.

Denis Colli Spalenza

Em 6 de novembro de 2015 17:04, phdiegues <notifications@github.com>
escreveu:

**Comment by phdiegues** [comment]
Fala Denis. No caso eu desabilitei o https no meu backend e funcionou.

**Comment by deniscsz** [comment]
Legal, provavelmente posso alterar para funcionar em ambas as situações,
vou ver o que deixei passar.

**Comment by phdiegues** [comment]
Big Artesanato


 Beleza amigo.

 

Obrigado mais uma vez pela atenção.


Big Artesanato

 

De: Denis Colli Spalenza [mailto:notifications@github.com] 
Enviada em: segunda-feira, 9 de novembro de 2015 11:56
Para: deniscsz/Magento-Sigep
Cc: phdiegues
Assunto: Re: [Magento-Sigep] Errinho (#1)

 

Legal, provavelmente posso alterar para funcionar em ambas as situações,
vou ver o que deixei passar.



—
Reply to this email directly or view <https://github.com/deniscsz/Magento-Sigep/issues/1#issuecomment-155068747>  it on GitHub.  <https://github.com/notifications/beacon/AGDCs2Ap0daWtAlaRXxPmWd3yg1bswcrks5pEJ2IgaJpZM4BJhLS.gif> 



---
Este email foi escaneado pelo Avast antivírus.
https://www.avast.com/antivirus

**Comment by az2009** [comment]
Olá Denis ao tentar exportar para layout sigep, retornando erro de envio de cabeçalho:
Cannot send headers; headers already sent in app/code/community/Xpd/Sigep/controllers/Adminhtml/Sales/OrderController.php, line 75
